CREATE TABLE  COMPANY_INFO
(
    ID BIGINT GENERATED  BY DEFAULT AS IDENTITY,
    NAME VARCHAR(250) NOT NULL,
    PHONE VARCHAR(15),
    PAN VARCHAR(100),
    ADDRESS VARCHAR(2000),
    PRIMARY KEY (ID)
);