CREATE TABLE APP_USER
(
    ID       VARCHAR(36) DEFAULT UUID() PRIMARY KEY,
    EMAIL    VARCHAR(250) NOT NULL,
    PASSWORD VARCHAR(4000)
);

CREATE TABLE ROLE
(
    ID      VARCHAR(36) DEFAULT UUID() PRIMARY KEY,
    ROLE    VARCHAR(250) NOT NULL,
    USER_ID VARCHAR(36) REFERENCES APP_USER (ID)
);