CREATE TABLE APP_USER
(
    ID BIGINT GENERATED  BY DEFAULT AS IDENTITY,
    EMAIL      VARCHAR(250) NOT NULL,
    FIRST_NAME VARCHAR(250) NOT NULL,
    LAST_NAME  VARCHAR(250) NOT NULL,
    PHONE      VARCHAR(250) NOT NULL,
    PASSWORD   VARCHAR(4000),
    COMPANY_ID BIGINT REFERENCES COMPANY_INFO(ID),
    PRIMARY KEY (ID)

);

CREATE TABLE ROLE
(
    ID BIGINT GENERATED  BY DEFAULT AS IDENTITY,
    ROLE  VARCHAR(250) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE USER_ROLE (
                           ID BIGINT GENERATED  BY DEFAULT AS IDENTITY,
                           ROLES_ID   BIGINT REFERENCES ROLE(ID),
                           APP_USER_ID  BIGINT REFERENCES APP_USER (ID),
                           PRIMARY KEY (ID)
);