CREATE TABLE  PRODUCT_ITEM
(
    ID BIGINT GENERATED  BY DEFAULT AS IDENTITY,
    NAME VARCHAR(250) NOT NULL,
    PRODUCT_ID BIGINT REFERENCES PRODUCT(ID),
    PRICE DOUBLE PRECISION NOT NULL,
    QUANTITY DOUBLE PRECISION NOT NULL,
    UNIT DOUBLE PRECISION NOT NULL,
    COMPANY_ID BIGINT NOT NULL REFERENCES COMPANY_INFO(ID),
    PRIMARY KEY (ID)
);