CREATE TABLE VENDOR
(
    ID BIGINT GENERATED  BY DEFAULT AS IDENTITY,
    NAME VARCHAR(250),
    PHONE VARCHAR(250),
    EMAIL VARCHAR(250),
    ADDRESS VARCHAR(250),
    COMPANY_ID BIGINT NOT NULL REFERENCES COMPANY_INFO(ID),
    PRIMARY KEY (ID)
);